/**
 * QUIZ BÍBLICO — Banco de dados
 * Categorias, dificuldades, perguntas e conquistas.
 * Cada pergunta: { cat, diff (1-4), q, opts:[correta, ...distratores], note }
 * A opção correta é sempre opts[0] — a interface embaralha na hora de exibir.
 */

window.QUIZ_CATEGORIES = [
    { id: 'bible',    icon: '📖', name: 'Conhecimento Bíblico' },
    { id: 'people',   icon: '👤', name: 'Personagens' },
    { id: 'places',   icon: '🗺️', name: 'Lugares' },
    { id: 'books',    icon: '📜', name: 'Livros' },
    { id: 'jesus',    icon: '✝️', name: 'Jesus' },
    { id: 'prophecy', icon: '🔥', name: 'Profecia' },
    { id: 'theology', icon: '🧠', name: 'Teologia' },
    { id: 'history',  icon: '📚', name: 'História' },
];

window.QUIZ_DIFFICULTIES = [
    { id: 1, name: 'Iniciante',      short: 'Fácil',   icon: 'ph-seedling',    xp: 10 },
    { id: 2, name: 'Intermediário',  short: 'Médio',   icon: 'ph-plant',       xp: 15 },
    { id: 3, name: 'Avançado',       short: 'Difícil', icon: 'ph-tree-evergreen', xp: 20 },
    { id: 4, name: 'Especialista',   short: 'Expert',  icon: 'ph-crown',       xp: 30 },
];

window.QUIZ_LEVEL_TITLES = [
    'Aprendiz', 'Discípulo', 'Estudante da Palavra', 'Conhecedor das Escrituras',
    'Escriba', 'Mestre da Palavra', 'Sábio', 'Erudito Bíblico',
    'Guardião da Palavra', 'Doutor das Escrituras'
];

// Versículos curtos sobre sabedoria/aprendizado, exibidos ao final de cada quiz.
window.QUIZ_ENCOURAGEMENT = [
    { ref: 'Provérbios 1:7', text: 'O temor do Senhor é o princípio do conhecimento.' },
    { ref: 'Provérbios 2:6', text: 'Porque o Senhor dá a sabedoria; da sua boca vêm o conhecimento e o entendimento.' },
    { ref: '2 Timóteo 2:15', text: 'Procura apresentar-te a Deus aprovado, obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.' },
    { ref: 'Salmos 119:105', text: 'Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.' },
    { ref: 'Tiago 1:5', text: 'E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente.' },
    { ref: 'Provérbios 9:10', text: 'O temor do Senhor é o princípio da sabedoria, e a ciência do Santo, a prudência.' },
    { ref: 'Josué 1:8', text: 'Não se aparte da tua boca o livro desta lei; antes medita nele dia e noite.' },
    { ref: 'Salmos 119:11', text: 'Escondi a tua palavra no meu coração, para não pecar contra ti.' },
    { ref: 'Romanos 12:2', text: 'Transformai-vos pela renovação da vossa mente.' },
    { ref: 'Colossenses 3:16', text: 'A palavra de Cristo habite em vós ricamente, em toda a sabedoria.' },
];

window.QUIZ_ACHIEVEMENTS = [
    { id: 'first_quiz',    icon: 'ph-flag-checkered', name: 'Primeiro Passo',        desc: 'Complete o seu primeiro quiz.' },
    { id: 'ten_quiz',      icon: 'ph-books',          name: 'Estudante Dedicado',    desc: 'Complete 10 quizzes.' },
    { id: 'fifty_quiz',    icon: 'ph-graduation-cap', name: 'Discípulo Constante',   desc: 'Complete 50 quizzes.' },
    { id: 'fifty_correct', icon: 'ph-check-circle',   name: 'Conhecedor',            desc: 'Acerte 50 perguntas no total.' },
    { id: 'hundred_correct', icon: 'ph-medal',        name: 'Mestre das Escrituras', desc: 'Acerte 100 perguntas no total.' },
    { id: 'perfect',       icon: 'ph-star',           name: 'Perfeccionista',        desc: 'Termine um quiz com 100% de acerto.' },
    { id: 'expert_perfect',icon: 'ph-crown',          name: 'Erudito',               desc: 'Gabarite um quiz no nível Especialista.' },
    { id: 'streak3',       icon: 'ph-fire',           name: 'Três Dias de Fé',       desc: 'Complete o Quiz do Dia 3 dias seguidos.' },
    { id: 'streak7',       icon: 'ph-fire-simple',    name: 'Uma Semana na Palavra', desc: 'Complete o Quiz do Dia 7 dias seguidos.' },
    { id: 'streak30',      icon: 'ph-flame',          name: 'Constância',            desc: 'Complete o Quiz do Dia 30 dias seguidos.' },
    { id: 'explorer',      icon: 'ph-compass',        name: 'Explorador Bíblico',    desc: 'Responda perguntas de todas as 8 categorias.' },
    { id: 'level5',        icon: 'ph-trophy',         name: 'Nível 5',               desc: 'Alcance o nível 5.' },
    { id: 'level10',       icon: 'ph-trophy-fill',    name: 'Nível 10',              desc: 'Alcance o nível 10.' },
    { id: 'mastery_bible',    icon: 'ph-book-open',    name: 'Sábio das Escrituras', desc: 'Acerte 20 perguntas de Conhecimento Bíblico.' },
    { id: 'mastery_people',   icon: 'ph-users-three',  name: 'Genealogista',        desc: 'Acerte 20 perguntas de Personagens.' },
    { id: 'mastery_places',   icon: 'ph-map-trifold',  name: 'Cartógrafo Bíblico',  desc: 'Acerte 20 perguntas de Lugares.' },
    { id: 'mastery_books',    icon: 'ph-scroll',       name: 'Bibliotecário',       desc: 'Acerte 20 perguntas de Livros.' },
    { id: 'mastery_jesus',    icon: 'ph-cross',        name: 'Discípulo Fiel',      desc: 'Acerte 20 perguntas sobre Jesus.' },
    { id: 'mastery_prophecy', icon: 'ph-fire',         name: 'Vidente',             desc: 'Acerte 20 perguntas de Profecia.' },
    { id: 'mastery_theology', icon: 'ph-brain',        name: 'Teólogo',             desc: 'Acerte 20 perguntas de Teologia.' },
    { id: 'mastery_history',  icon: 'ph-clock-counter-clockwise', name: 'Historiador', desc: 'Acerte 20 perguntas de História.' },
];

window.QUIZ_QUESTIONS = [
    /* ═════════════════ BIBLE KNOWLEDGE ═════════════════ */
    { cat:'bible', diff:1, q:'Quantos livros tem a Bíblia na tradição protestante?', opts:['66','73','39','27'], note:'São 39 livros no Antigo Testamento e 27 no Novo Testamento, totalizando 66.' },
    { cat:'bible', diff:1, q:'Em quantas partes principais a Bíblia se divide?', opts:['Antigo e Novo Testamento','Torá e Talmude','Evangelhos e Cartas','Lei e Profetas'], note:'A divisão clássica é Antigo Testamento (antes de Cristo) e Novo Testamento (após Cristo).' },
    { cat:'bible', diff:1, q:'Qual é o primeiro livro da Bíblia?', opts:['Gênesis','Êxodo','Levítico','Números'], note:'Gênesis significa "origem" e narra a criação do mundo.' },
    { cat:'bible', diff:1, q:'Qual é o último livro da Bíblia?', opts:['Apocalipse','Judas','Malaquias','Atos'], note:'Apocalipse, escrito por João, encerra o cânon com a visão da nova criação.' },
    { cat:'bible', diff:2, q:'Qual língua predominou na escrita do Antigo Testamento?', opts:['Hebraico','Grego','Latim','Aramaico'], note:'Pequenas partes de Daniel e Esdras foram escritas em aramaico, mas o hebraico predomina.' },
    { cat:'bible', diff:2, q:'Quantos livros compõem o Novo Testamento?', opts:['27','39','66','21'], note:'Do Evangelho de Mateus ao Apocalipse, são 27 livros.' },
    { cat:'bible', diff:2, q:'Qual é o livro mais longo da Bíblia em número de capítulos?', opts:['Salmos','Isaías','Gênesis','Jeremias'], note:'Salmos tem 150 capítulos — uma coletânea de cânticos e orações.' },
    { cat:'bible', diff:2, q:'Qual é o menor livro do Novo Testamento em número de versículos?', opts:['2 João','3 João','Filemom','Judas'], note:'2 João tem apenas 13 versículos, uma breve carta pessoal do apóstolo.' },
    { cat:'bible', diff:3, q:'Em que língua foi escrito originalmente o Novo Testamento?', opts:['Grego koiné','Hebraico','Latim','Aramaico'], note:'O grego koiné era a língua comum do Mediterrâneo oriental no primeiro século.' },
    { cat:'bible', diff:3, q:'Qual destes é considerado o versículo mais curto da Bíblia em português?', opts:['"Chorou Jesus."','"Orai sem cessar."','"Deus é amor."','"Regozijai-vos sempre."'], note:'É João 11:35 — apenas duas palavras, diante do luto de Lázaro.' },
    { cat:'bible', diff:3, q:'Quantos salmos existem no livro de Salmos?', opts:['150','120','100','175'], note:'Os salmos vão desde lamentos até cânticos de louvor, cobrindo toda gama de emoção humana.' },
    { cat:'bible', diff:3, q:'Como são chamados os livros aceitos no cânon católico/ortodoxo, mas não no protestante, como Tobias e Macabeus?', opts:['Deuterocanônicos (apócrifos)','Pseudoepígrafos','Sinóticos','Pastorais'], note:'"Deuterocanônico" significa "segundo cânon" — aceito mais tarde por parte da tradição cristã.' },
    { cat:'bible', diff:4, q:'Qual verso é tradicionalmente apontado como o texto central de toda a Bíblia?', opts:['Salmos 118:8','João 3:16','Gênesis 1:1','Salmos 23:1'], note:'"Melhor é confiar no Senhor do que confiar no homem" — uma curiosidade de contagem, não uma doutrina.' },
    { cat:'bible', diff:4, q:'Aproximadamente quantos autores humanos são tradicionalmente associados à composição da Bíblia?', opts:['Cerca de 40','Exatamente 12','Cerca de 100','Apenas 4'], note:'Escrita ao longo de cerca de 1.500 anos, por pastores, reis, profetas, pescadores e médicos.' },
    { cat:'bible', diff:4, q:'Qual concílio do século IV é frequentemente citado por ajudar a consolidar a lista de livros do Novo Testamento?', opts:['Concílio de Cartago','Concílio de Trento','Concílio de Niceia','Concílio Vaticano I'], note:'Realizado em 397 d.C.; Niceia (325 d.C.), ao contrário do que muitos pensam, tratou de outros temas, não do cânon.' },
    { cat:'bible', diff:4, q:'Em quantos anos, aproximadamente, a Bíblia foi escrita, do primeiro ao último livro?', opts:['Cerca de 1.500 anos','Cerca de 200 anos','Cerca de 3.000 anos','Cerca de 500 anos'], note:'Um testemunho notável de coerência ao longo de tantos séculos e autores diferentes.' },

    /* ═════════════════ PEOPLE ═════════════════ */
    { cat:'people', diff:1, q:'Quem construiu a arca para sobreviver ao dilúvio?', opts:['Noé','Abraão','Moisés','Davi'], note:'Noé obedeceu a Deus mesmo sem nunca ter visto chover (Gênesis 6-9).' },
    { cat:'people', diff:1, q:'Quem liderou o povo de Israel para fora da escravidão no Egito?', opts:['Moisés','Josué','Arão','Davi'], note:'Moisés confrontou o Faraó e guiou o povo através do Mar Vermelho.' },
    { cat:'people', diff:1, q:'Quem foi o primeiro rei de Israel?', opts:['Saul','Davi','Salomão','Samuel'], note:'Saul foi ungido pelo profeta Samuel a pedido do povo (1 Samuel 10).' },
    { cat:'people', diff:1, q:'Quem derrotou o gigante Golias com uma funda e uma pedra?', opts:['Davi','Sansão','Josué','Gideão'], note:'Um jovem pastor confiando em Deus venceu um guerreiro filisteu experiente (1 Samuel 17).' },
    { cat:'people', diff:2, q:'Quem foi vendido como escravo pelos próprios irmãos e depois se tornou governador do Egito?', opts:['José','Benjamim','Rúben','Judá'], note:'"Vós intentastes o mal contra mim, porém Deus o intentou para o bem" (Gênesis 50:20).' },
    { cat:'people', diff:2, q:'Quem foi a esposa de Abraão que riu ao ouvir que teria um filho na velhice?', opts:['Sara','Rebeca','Raquel','Lia'], note:'Ela deu à luz Isaque, cujo nome significa "riso" (Gênesis 18 e 21).' },
    { cat:'people', diff:2, q:'Qual profeta foi engolido por um grande peixe ao fugir do chamado de Deus?', opts:['Jonas','Elias','Eliseu','Jeremias'], note:'Depois de três dias no peixe, Jonas pregou em Nínive (Jonas 1-3).' },
    { cat:'people', diff:2, q:'Quem traiu Jesus por trinta moedas de prata?', opts:['Judas Iscariotes','Pedro','Tomé','Simão'], note:'Um dos doze apóstolos, cujo remorso o levou a devolver o dinheiro (Mateus 26-27).' },
    { cat:'people', diff:3, q:'Quem foi o sogro de Moisés, sacerdote de Midiã?', opts:['Jetro','Labão','Faraó','Coré'], note:'Jetro também aconselhou Moisés a delegar a liderança do povo (Êxodo 18).' },
    { cat:'people', diff:3, q:'Qual rei de Israel era famoso por sua sabedoria e construiu o primeiro Templo em Jerusalém?', opts:['Salomão','Davi','Roboão','Ezequias'], note:'Salomão pediu sabedoria a Deus em vez de riquezas (1 Reis 3).' },
    { cat:'people', diff:3, q:'Quem foi a profetisa e juíza que liderou Israel antes do período dos reis?', opts:['Débora','Rute','Ana','Hulda'], note:'Ela julgava sob uma palmeira e liderou Baraque à vitória (Juízes 4-5).' },
    { cat:'people', diff:3, q:'Qual apóstolo ficou conhecido por duvidar da ressurreição de Jesus até ver as marcas dos cravos?', opts:['Tomé','André','Filipe','Mateus'], note:'"Bem-aventurados os que não viram e creram" (João 20:29).' },
    { cat:'people', diff:4, q:'Quem foi o sucessor de Moisés na liderança de Israel?', opts:['Josué','Calebe','Finéias','Otniel'], note:'Josué liderou a conquista da Terra Prometida (Livro de Josué).' },
    { cat:'people', diff:4, q:'Qual rainha persa arriscou a vida para salvar seu povo da destruição?', opts:['Ester','Vasti','Atalia','Jezabel'], note:'"E quem sabe se para tal tempo como este chegaste a este reino?" (Ester 4:14).' },
    { cat:'people', diff:4, q:'Quem foi Barnabé em relação ao apóstolo Paulo?', opts:['Seu companheiro de missão','Seu carcereiro','Seu pai espiritual apenas','Seu opositor'], note:'Barnabé, o "filho da consolação", viajou com Paulo em sua primeira jornada missionária (Atos 13).' },
    { cat:'people', diff:4, q:'Qual profeta confrontou o rei Davi após seu pecado com Bate-Seba, usando a parábola da ovelhinha?', opts:['Natã','Gade','Samuel','Aías'], note:'"Tu és este homem!" (2 Samuel 12:7) levou Davi ao arrependimento.' },

    /* ═════════════════ PLACES ═════════════════ */
    { cat:'places', diff:1, q:'Em que cidade Jesus nasceu?', opts:['Belém','Nazaré','Jerusalém','Cafarnaum'], note:'Cumprindo a profecia de Miqueias 5:2, "Belém... de ti me sairá o que há de ser Senhor em Israel."' },
    { cat:'places', diff:1, q:'Em que cidade Jesus cresceu com sua família?', opts:['Nazaré','Belém','Jerusalém','Jope'], note:'Por isso Jesus foi chamado de "Nazareno" (Mateus 2:23).' },
    { cat:'places', diff:1, q:'Qual é a cidade santa central para judeus, cristãos e muçulmanos?', opts:['Jerusalém','Roma','Meca','Damasco'], note:'Lar do Templo de Salomão e cenário de eventos-chave em toda a Bíblia.' },
    { cat:'places', diff:1, q:'De qual país o povo de Israel saiu durante o Êxodo?', opts:['Egito','Babilônia','Assíria','Pérsia'], note:'Depois de mais de 400 anos de escravidão, Deus os libertou pela mão de Moisés.' },
    { cat:'places', diff:2, q:'Em qual monte Moisés recebeu os Dez Mandamentos?', opts:['Monte Sinai','Monte Sião','Monte das Oliveiras','Monte Carmelo'], note:'Deus desceu em fogo sobre o monte, e a terra tremeu (Êxodo 19-20).' },
    { cat:'places', diff:2, q:'Em qual rio Jesus foi batizado por João Batista?', opts:['Rio Jordão','Rio Nilo','Rio Eufrates','Mar da Galileia'], note:'Ali os céus se abriram e o Espírito desceu como pomba (Mateus 3:16).' },
    { cat:'places', diff:2, q:'Qual cidade foi destruída por Deus junto com Gomorra, por causa de sua maldade?', opts:['Sodoma','Jericó','Nínive','Tiro'], note:'Ló e sua família escaparam antes da destruição (Gênesis 19).' },
    { cat:'places', diff:2, q:'Em qual região da Palestina ficava a cidade de Nazaré?', opts:['Galileia','Judeia','Samaria','Perea'], note:'A Galileia era uma região agrícola no norte, onde Jesus realizou boa parte de seu ministério.' },
    { cat:'places', diff:3, q:'Para onde o povo de Judá foi levado em cativeiro pelos babilônios?', opts:['Babilônia','Egito','Assíria','Pérsia'], note:'O exílio durou cerca de 70 anos, cumprindo a profecia de Jeremias.' },
    { cat:'places', diff:3, q:'Em qual ilha o apóstolo João recebeu a visão registrada no Apocalipse?', opts:['Patmos','Chipre','Creta','Malta'], note:'João estava exilado ali "por causa da palavra de Deus" (Apocalipse 1:9).' },
    { cat:'places', diff:3, q:'Qual cidade era a capital do poderoso Império Assírio?', opts:['Nínive','Babilônia','Susã','Tiro'], note:'Foi a Nínive que Jonas foi enviado para pregar arrependimento.' },
    { cat:'places', diff:3, q:'Em qual jardim Jesus orou angustiado antes de ser preso?', opts:['Getsêmani','Éden','Gólgota','Cedrom'], note:'"Ainda que não seja como eu quero, mas como tu queres" (Mateus 26:39).' },
    { cat:'places', diff:4, q:'Qual era o nome do lugar onde Jesus foi crucificado, cujo nome significa "lugar da Caveira"?', opts:['Gólgota','Getsêmani','Betesda','Emaús'], note:'Fora dos muros de Jerusalém, também chamado de Calvário em latim.' },
    { cat:'places', diff:4, q:'Em qual cidade Paulo teve seu encontro transformador com Jesus, a caminho de perseguir cristãos?', opts:['Damasco','Antioquia','Tarso','Éfeso'], note:'Uma luz do céu o cegou, e ele ouviu: "Saulo, Saulo, por que me persegues?" (Atos 9).' },
    { cat:'places', diff:4, q:'Qual era a capital do Reino do Norte (Israel) após a divisão do reino unido?', opts:['Samaria','Siquém','Dã','Betel'], note:'Construída pelo rei Onri, tornou-se símbolo da idolatria do reino do norte.' },
    { cat:'places', diff:4, q:'Em qual região Abraão viveu antes de ser chamado por Deus a ir para Canaã?', opts:['Ur dos Caldeus','Harã apenas','Egito','Midiã'], note:'"Sai da tua terra... para a terra que eu te mostrarei" (Gênesis 12:1).' },

    /* ═════════════════ BOOKS ═════════════════ */
    { cat:'books', diff:1, q:'Quantos evangelhos existem no Novo Testamento?', opts:['4','3','5','2'], note:'Mateus, Marcos, Lucas e João — quatro relatos da vida de Jesus.' },
    { cat:'books', diff:1, q:'Qual livro bíblico narra a criação do mundo?', opts:['Gênesis','Êxodo','Salmos','Apocalipse'], note:'"No princípio criou Deus os céus e a terra" (Gênesis 1:1).' },
    { cat:'books', diff:1, q:'Qual livro é uma coletânea de cânticos e orações usados em adoração?', opts:['Salmos','Provérbios','Cântico dos Cânticos','Lamentações'], note:'Muitos salmos são atribuídos a Davi, mas há também os de Asafe e dos filhos de Corá.' },
    { cat:'books', diff:1, q:'Qual é o último livro do Novo Testamento?', opts:['Apocalipse','Judas','2 Pedro','Hebreus'], note:'Escrito pelo apóstolo João, revela a vitória final de Cristo.' },
    { cat:'books', diff:2, q:'Quais são os quatro evangelhos, em ordem no Novo Testamento?', opts:['Mateus, Marcos, Lucas e João','Marcos, Mateus, João e Lucas','Lucas, João, Mateus e Marcos','João, Mateus, Marcos e Lucas'], note:'Cada evangelho apresenta um retrato distinto de Jesus para um público diferente.' },
    { cat:'books', diff:2, q:'Qual livro narra a saída de Israel da escravidão no Egito?', opts:['Êxodo','Gênesis','Levítico','Números'], note:'O nome "Êxodo" significa literalmente "saída".' },
    { cat:'books', diff:2, q:'A quem é tradicionalmente atribuída a autoria da maioria das epístolas do Novo Testamento?', opts:['Paulo','Pedro','Tiago','João'], note:'Paulo escreveu cartas a igrejas como Roma, Corinto, Gálatas e Filipos.' },
    { cat:'books', diff:2, q:'Qual livro reúne principalmente ditos de sabedoria atribuídos a Salomão?', opts:['Provérbios','Eclesiastes','Jó','Cântico dos Cânticos'], note:'Provérbios contrasta o caminho da sabedoria com o da insensatez.' },
    { cat:'books', diff:3, q:'Qual livro do Antigo Testamento não menciona o nome de Deus diretamente no texto?', opts:['Ester','Rute','Jó','Jonas'], note:'Mesmo sem citar Deus, o livro mostra sua providência silenciosa protegendo o povo judeu.' },
    { cat:'books', diff:3, q:'Quais três evangelhos são chamados de "sinóticos" por compartilharem estrutura e conteúdo semelhantes?', opts:['Mateus, Marcos e Lucas','Mateus, Marcos e João','Marcos, Lucas e João','Mateus, Lucas e João'], note:'"Sinótico" vem do grego e significa "ver junto" — um mesmo panorama sob três perspectivas.' },
    { cat:'books', diff:3, q:'Qual epístola é uma carta pessoal de Paulo pedindo que um escravo fugitivo seja recebido de volta com perdão?', opts:['Filemom','Tito','2 Timóteo','Colossenses'], note:'Paulo intercede por Onésimo, agora "irmão amado" em Cristo (Filemom 16).' },
    { cat:'books', diff:3, q:'Quem é tradicionalmente considerado o autor do livro de Atos dos Apóstolos?', opts:['Lucas','Marcos','Tiago','Judas'], note:'O mesmo autor do terceiro evangelho, um médico e companheiro de Paulo.' },
    { cat:'books', diff:4, q:'Qual profeta menor escreveu o livro mais curto do Antigo Testamento, um único oráculo contra Edom?', opts:['Obadias','Ageu','Naum','Malaquias'], note:'Apenas 21 versículos anunciando o juízo sobre o orgulho de Edom.' },
    { cat:'books', diff:4, q:'Qual livro do Antigo Testamento é estruturado como poemas acrósticos em hebraico?', opts:['Lamentações','Provérbios','Eclesiastes','Salmos apenas'], note:'Cada capítulo segue (ou ecoa) as 22 letras do alfabeto hebraico, lamentando a queda de Jerusalém.' },
    { cat:'books', diff:4, q:'Qual epístola tem autoria debatida entre estudiosos, sem certeza se foi escrita por Paulo?', opts:['Hebreus','Romanos','Gálatas','Efésios'], note:'O próprio texto não se identifica, ao contrário da maioria das cartas paulinas.' },
    { cat:'books', diff:4, q:'Qual livro sapiencial explora o sofrimento humano por meio da história de um homem íntegro que perde tudo?', opts:['Jó','Eclesiastes','Provérbios','Lamentações'], note:'Jó questiona, sofre e, ao final, encontra a resposta na própria presença de Deus.' },

    /* ═════════════════ JESUS ═════════════════ */
    { cat:'jesus', diff:1, q:'Qual é o nome da mãe de Jesus?', opts:['Maria','Marta','Ana','Isabel'], note:'Uma jovem de Nazaré escolhida para gerar o Salvador (Lucas 1:26-38).' },
    { cat:'jesus', diff:1, q:'Quantos apóstolos Jesus escolheu para segui-lo de perto?', opts:['12','7','10','70'], note:'Os doze representam simbolicamente as doze tribos de Israel.' },
    { cat:'jesus', diff:1, q:'Qual foi o primeiro milagre público de Jesus, realizado em um casamento?', opts:['Transformar água em vinho','Curar um cego','Andar sobre as águas','Multiplicar pães'], note:'Aconteceu em Caná da Galileia, a pedido de sua mãe (João 2:1-11).' },
    { cat:'jesus', diff:1, q:'Qual celebração cristã marca a ressurreição de Jesus?', opts:['Páscoa','Pentecostes','Natal','Ascensão'], note:'O coração da fé cristã: "Ele não está aqui, ressuscitou!" (Lucas 24:6).' },
    { cat:'jesus', diff:2, q:'Como é conhecido o famoso discurso de Jesus que inclui as Bem-Aventuranças?', opts:['Sermão do Monte','Discurso do Templo','Parábola do Semeador','Oração Sacerdotal'], note:'Registrado em Mateus 5-7, apresenta os valores do Reino de Deus.' },
    { cat:'jesus', diff:2, q:'No relato da multiplicação para 5 mil homens, com quantos pães e peixes Jesus começou?', opts:['5 pães e 2 peixes','7 pães e 3 peixes','2 pães e 5 peixes','12 pães e 1 peixe'], note:'Um menino ofereceu o pouco que tinha, e Jesus multiplicou (João 6:9).' },
    { cat:'jesus', diff:2, q:'Qual apóstolo negou conhecer Jesus três vezes antes do galo cantar?', opts:['Pedro','João','Tiago','André'], note:'Depois, restaurado por Jesus, Pedro se tornou um dos pilares da igreja (João 21).' },
    { cat:'jesus', diff:2, q:'Em qual cidade Jesus ressuscitou Lázaro dentre os mortos?', opts:['Betânia','Jericó','Cafarnaum','Emaús'], note:'"Eu sou a ressurreição e a vida", disse Jesus a Marta antes do milagre (João 11:25).' },
    { cat:'jesus', diff:3, q:'Qual título Jesus mais usava para si mesmo, unindo humanidade e uma figura profética de Daniel?', opts:['Filho do Homem','Filho de Davi','Rabi','Cordeiro de Deus'], note:'Aponta tanto para sua humildade humana quanto para a autoridade celestial de Daniel 7:13-14.' },
    { cat:'jesus', diff:3, q:'Quantos dias Jesus jejuou no deserto antes de ser tentado por Satanás?', opts:['40 dias','7 dias','3 dias','12 dias'], note:'Um eco dos 40 anos de Israel no deserto — mas dessa vez, sem ceder à tentação (Mateus 4).' },
    { cat:'jesus', diff:3, q:'Segundo a tradição cristã, em qual monte teria ocorrido a Transfiguração de Jesus?', opts:['Monte Tabor','Monte Sinai','Monte Sião','Monte Ebal'], note:'Os evangelhos não citam o nome; a tradição posterior identificou o Tabor.' },
    { cat:'jesus', diff:3, q:'Qual parábola de Jesus fala de um pai que recebe de volta o filho que desperdiçou sua herança?', opts:['O Filho Pródigo','O Bom Samaritano','O Semeador','A Ovelha Perdida'], note:'Uma imagem viva da graça e do perdão do Pai (Lucas 15:11-32).' },
    { cat:'jesus', diff:4, q:'Segundo o Evangelho de Lucas, quais foram as últimas palavras de Jesus na cruz?', opts:['"Pai, em tuas mãos entrego o meu espírito"','"Está consumado"','"Meu Deus, meu Deus, por que me desamparaste?"','"Tenho sede"'], note:'Lucas 23:46 registra um ato final de confiança total no Pai.' },
    { cat:'jesus', diff:4, q:'Qual termo grego do Sermão do Monte é traduzido como "Bem-aventurados"?', opts:['Makarios','Agape','Logos','Kerigma'], note:'"Makarios" descreve uma felicidade profunda, ligada à bênção de Deus, não a circunstâncias.' },
    { cat:'jesus', diff:4, q:'Quantas vezes os evangelhos registram explicitamente Jesus chorando?', opts:['Duas vezes','Nenhuma vez','Cinco vezes','Uma vez'], note:'Por Lázaro (João 11:35) e por Jerusalém (Lucas 19:41) — mostrando sua humanidade plena.' },
    { cat:'jesus', diff:4, q:'Qual é o significado do nome profético "Emanuel", aplicado a Jesus?', opts:['"Deus conosco"','"Salvador do mundo"','"Filho amado"','"Príncipe da paz"'], note:'Profetizado em Isaías 7:14 e citado em Mateus 1:23 no nascimento de Jesus.' },

    /* ═════════════════ PROPHECY ═════════════════ */
    { cat:'prophecy', diff:1, q:'Qual profeta foi engolido por um grande peixe por fugir do chamado de Deus?', opts:['Jonas','Elias','Isaías','Amós'], note:'Depois pregou em Nínive, e a cidade inteira se arrependeu (Jonas 3).' },
    { cat:'prophecy', diff:1, q:'Qual livro profético registra a visão de Daniel com quatro grandes reinos?', opts:['Daniel','Ezequiel','Isaías','Zacarias'], note:'Daniel interpretou sonhos de reis e teve visões próprias sobre impérios futuros.' },
    { cat:'prophecy', diff:1, q:'Qual profeta subiu ao céu em um redemoinho, num carro de fogo?', opts:['Elias','Eliseu','Enoque','Moisés'], note:'Seu discípulo Eliseu recebeu porção dobrada de seu espírito (2 Reis 2).' },
    { cat:'prophecy', diff:1, q:'Qual profeta ungiu Davi como rei quando ele ainda era um jovem pastor?', opts:['Samuel','Natã','Gade','Aías'], note:'Deus disse a Samuel: "o Senhor olha para o coração" (1 Samuel 16:7).' },
    { cat:'prophecy', diff:2, q:'Qual profeta é chamado de "profeta chorão" por causa do livro de Lamentações?', opts:['Jeremias','Ezequiel','Joel','Habacuque'], note:'Ele lamentou profundamente a destruição de Jerusalém pelos babilônios.' },
    { cat:'prophecy', diff:2, q:'Qual profeta teve a visão do "vale de ossos secos" que voltam à vida?', opts:['Ezequiel','Daniel','Jeremias','Isaías'], note:'Uma imagem da restauração espiritual de Israel (Ezequiel 37).' },
    { cat:'prophecy', diff:2, q:'Qual profeta menor comparou o amor de Deus por Israel a um casamento com uma esposa infiel?', opts:['Oséias','Joel','Amós','Miquéias'], note:'Deus mandou que ele se casasse com Gômer como sinal profético vivo.' },
    { cat:'prophecy', diff:2, q:'Qual profecia de Isaías é associada ao nascimento de Jesus, mencionando uma virgem que conceberá?', opts:['Isaías 7:14','Isaías 40:3','Isaías 61:1','Isaías 9:2'], note:'"Eis que a virgem conceberá, e dará à luz um filho" — citada em Mateus 1:23.' },
    { cat:'prophecy', diff:3, q:'Qual profeta confrontou os profetas de Baal em um duelo no Monte Carmelo?', opts:['Elias','Eliseu','Miquéias','Jeremias'], note:'"Se o Senhor é Deus, segui-o" (1 Reis 18:21) — e o fogo do céu respondeu.' },
    { cat:'prophecy', diff:3, q:'Qual profeta menor anunciou a queda final de Nínive, capital da Assíria?', opts:['Naum','Jonas','Obadias','Habacuque'], note:'Diferente de Jonas, que viu Nínive se arrepender, Naum profetizou sua destruição definitiva.' },
    { cat:'prophecy', diff:3, q:'Segundo Jeremias, quantos anos duraria o exílio de Judá na Babilônia?', opts:['70 anos','40 anos','12 anos','100 anos'], note:'Essa profecia foi confirmada quando Daniel a estudou (Daniel 9:2).' },
    { cat:'prophecy', diff:3, q:'Qual profeta teve um chamado dramático no Templo, vendo serafins clamando "Santo, santo, santo"?', opts:['Isaías','Ezequiel','Jeremias','Zacarias'], note:'"Eis-me aqui, envia-me a mim" foi sua resposta (Isaías 6:8).' },
    { cat:'prophecy', diff:4, q:'Qual profeta menor anunciou o "Dia do Senhor" por meio de uma devastadora praga de gafanhotos?', opts:['Joel','Ageu','Sofonias','Malaquias'], note:'Ele também profetizou o derramar do Espírito "sobre toda carne" (Joel 2:28), citado em Atos 2.' },
    { cat:'prophecy', diff:4, q:'No livro de Daniel, o que representava a estátua com cabeça de ouro no sonho de Nabucodonosor?', opts:['Uma sequência de impérios mundiais','O Templo de Jerusalém','O próprio Nabucodonosor apenas','O povo de Israel'], note:'Ouro, prata, bronze, ferro e barro simbolizam impérios que se sucederiam (Daniel 2).' },
    { cat:'prophecy', diff:4, q:'Qual profeta foi instruído por Deus a se casar com uma mulher infiel como símbolo da relação de Israel com Deus?', opts:['Oséias','Ezequiel','Jeremias','Isaías'], note:'Seu casamento com Gômer ilustrava tanto a infidelidade de Israel quanto o amor incansável de Deus.' },
    { cat:'prophecy', diff:4, q:'Qual capítulo de Isaías descreve o Servo Sofredor, "traspassado por nossas transgressões"?', opts:['Isaías 53','Isaías 40','Isaías 6','Isaías 61'], note:'Um dos textos messiânicos mais citados no Novo Testamento em referência a Jesus.' },

    /* ═════════════════ THEOLOGY ═════════════════ */
    { cat:'theology', diff:1, q:'Qual termo descreve a crença de que Deus é um só ser em três pessoas: Pai, Filho e Espírito Santo?', opts:['Trindade','Encarnação','Justificação','Aliança'], note:'Um mistério central da fé cristã, difícil de resumir, mas presente em toda a Escritura.' },
    { cat:'theology', diff:1, q:'Qual palavra descreve o favor gratuito e imerecido de Deus para com as pessoas?', opts:['Graça','Lei','Sacrifício','Tradição'], note:'"Pela graça sois salvos, por meio da fé... não vem de vós, é dom de Deus" (Efésios 2:8).' },
    { cat:'theology', diff:1, q:'Como se chama o ato de reconhecer os próprios pecados e se voltar para Deus?', opts:['Arrependimento','Batismo','Jejum','Ordenação'], note:'É o primeiro passo da resposta humana ao chamado de Deus.' },
    { cat:'theology', diff:1, q:'Qual termo descreve a crença de que a Bíblia é a palavra de Deus dada por meio de autores humanos?', opts:['Inspiração','Revelação apenas','Tradução','Interpretação'], note:'"Toda a Escritura é divinamente inspirada" (2 Timóteo 3:16).' },
    { cat:'theology', diff:2, q:'Qual termo descreve a crença de que Jesus é totalmente Deus e totalmente humano ao mesmo tempo?', opts:['Encarnação','Trindade','Ressurreição','Ascensão'], note:'"O Verbo se fez carne, e habitou entre nós" (João 1:14).' },
    { cat:'theology', diff:2, q:'Como se chama a promessa solene entre Deus e seu povo, como a feita com Abraão?', opts:['Aliança','Lei','Profecia','Parábola'], note:'Deus prometeu a Abraão: "Farei de ti uma grande nação" (Gênesis 12:2).' },
    { cat:'theology', diff:2, q:'Qual termo descreve a ideia de que o crente é declarado justo diante de Deus pela fé, não pelas obras?', opts:['Justificação','Santificação','Glorificação','Regeneração'], note:'Um tema central nas cartas de Paulo, especialmente Romanos e Gálatas.' },
    { cat:'theology', diff:2, q:'Como se chama a doutrina sobre a volta futura de Jesus à Terra?', opts:['Segunda Vinda','Primeira Aliança','Transfiguração','Pentecostes'], note:'Um evento aguardado com esperança em toda a tradição cristã, embora os detalhes sejam debatidos.' },
    { cat:'theology', diff:3, q:'Qual termo descreve o processo contínuo de um cristão se tornar mais semelhante a Cristo ao longo da vida?', opts:['Santificação','Justificação','Expiação','Conversão'], note:'Diferente da justificação (um ato único), a santificação é um processo ao longo da vida.' },
    { cat:'theology', diff:3, q:'Como se chama a doutrina de que a morte de Jesus paga o preço pelo pecado da humanidade?', opts:['Expiação','Encarnação','Predestinação','Escatologia'], note:'"Ele foi traspassado pelas nossas transgressões" (Isaías 53:5).' },
    { cat:'theology', diff:3, q:'Qual termo descreve a crença de que todos nascem com uma inclinação ao pecado, herdada desde Adão?', opts:['Pecado original','Livre-arbítrio','Predestinação','Graça comum'], note:'Um tema discutido desde Paulo (Romanos 5) e debatido de formas diferentes entre tradições cristãs.' },
    { cat:'theology', diff:3, q:'Como é chamada a celebração cristã que relembra a última ceia de Jesus com o pão e o vinho?', opts:['Ceia do Senhor (Eucaristia)','Batismo','Pentecostes','Consagração'], note:'Instituída na última ceia: "Fazei isto em memória de mim" (Lucas 22:19).' },
    { cat:'theology', diff:4, q:'Qual termo teológico, presente em Filipenses 2, descreve o "esvaziamento" de Jesus ao se tornar humano?', opts:['Kenosis','Parusia','Kerigma','Doxologia'], note:'"Esvaziou-se a si mesmo, tomando a forma de servo" (Filipenses 2:7).' },
    { cat:'theology', diff:4, q:'Como se chama o estudo teológico sobre os últimos eventos: julgamento, ressurreição, céu e inferno?', opts:['Escatologia','Soteriologia','Cristologia','Eclesiologia'], note:'Do grego "eschatos", que significa "último" ou "final".' },
    { cat:'theology', diff:4, q:'Qual termo descreve o conjunto de livros considerados oficialmente inspirados e autoritativos por uma tradição religiosa?', opts:['Cânon','Concílio','Concordância','Apócrifo'], note:'Vem do grego "kanon", que significa "régua" ou "padrão de medida".' },
    { cat:'theology', diff:4, q:'Como se chama o estudo teológico sobre a natureza e a obra do Espírito Santo?', opts:['Pneumatologia','Cristologia','Angelologia','Hamartiologia'], note:'Do grego "pneuma", que significa "espírito" ou "sopro".' },

    /* ═════════════════ HISTORY ═════════════════ */
    { cat:'history', diff:1, q:'Em qual país os hebreus estavam escravizados antes do Êxodo?', opts:['Egito','Babilônia','Assíria','Canaã'], note:'Por mais de 400 anos, até que Deus os libertou pela mão de Moisés.' },
    { cat:'history', diff:1, q:'Segundo a tradição bíblica, quantos anos os israelitas vagaram pelo deserto antes de entrar na Terra Prometida?', opts:['40 anos','10 anos','70 anos','25 anos'], note:'Uma consequência da falta de fé da geração que temeu entrar em Canaã (Números 14).' },
    { cat:'history', diff:1, q:'O reino de qual rei foi dividido em Israel (norte) e Judá (sul) logo após sua morte?', opts:['Salomão','Davi','Saul','Roboão'], note:'A divisão ocorreu no reinado de seu filho Roboão, por causa de decisões impopulares (1 Reis 12).' },
    { cat:'history', diff:1, q:'Em qual cidade nasceu a igreja cristã, no dia de Pentecostes?', opts:['Jerusalém','Antioquia','Roma','Corinto'], note:'O Espírito Santo desceu sobre os discípulos reunidos (Atos 2).' },
    { cat:'history', diff:2, q:'Qual império destruiu o Reino do Norte (Israel) em 722 a.C.?', opts:['Império Assírio','Império Babilônico','Império Persa','Império Romano'], note:'As dez tribos do norte foram dispersas e, em grande parte, assimiladas.' },
    { cat:'history', diff:2, q:'Qual império levou o povo de Judá ao cativeiro na Babilônia, por volta de 586 a.C.?', opts:['Império Babilônico','Império Assírio','Império Grego','Império Persa'], note:'Jerusalém e o Templo de Salomão foram destruídos nessa conquista.' },
    { cat:'history', diff:2, q:'Qual imperador persa autorizou o retorno dos judeus a Jerusalém e a reconstrução do Templo?', opts:['Ciro, o Grande','Dario','Xerxes','Artaxerxes'], note:'Cumprindo uma profecia de Isaías escrita anos antes do seu nascimento (Isaías 44:28).' },
    { cat:'history', diff:2, q:'Sob o domínio de qual império os eventos do Novo Testamento aconteceram?', opts:['Império Romano','Império Grego','Império Persa','Império Babilônico'], note:'As estradas e a paz romana ("Pax Romana") ajudaram na expansão do cristianismo primitivo.' },
    { cat:'history', diff:3, q:'Quem liderou a reconstrução dos muros de Jerusalém após o retorno do exílio babilônico?', opts:['Neemias','Esdras','Zorobabel','Ageu'], note:'Apesar da oposição, o muro foi reconstruído em apenas 52 dias (Neemias 6:15).' },
    { cat:'history', diff:3, q:'Qual sacerdote e escriba liderou uma reforma espiritual e a leitura pública da Lei após o exílio?', opts:['Esdras','Neemias','Malaquias','Zacarias'], note:'Ele "tinha preparado o seu coração para buscar a lei do Senhor" (Esdras 7:10).' },
    { cat:'history', diff:3, q:'Qual celebração judaica, ainda observada hoje, comemora a libertação da escravidão no Egito?', opts:['Páscoa judaica (Pessach)','Yom Kipur','Sucot','Hanucá'], note:'A mesma festa que Jesus celebrava com seus discípulos na última ceia.' },
    { cat:'history', diff:3, q:'Quem foi o primeiro mártir cristão, registrado no livro de Atos?', opts:['Estêvão','Tiago','Filipe','Barnabé'], note:'Ele orou por seus algozes ao morrer: "Não lhes imputes este pecado" (Atos 7:60).' },
    { cat:'history', diff:4, q:'Qual concílio da igreja primitiva, narrado em Atos 15, decidiu que gentios convertidos não precisavam seguir toda a lei mosaica?', opts:['Concílio de Jerusalém','Concílio de Niceia','Concílio de Cartago','Concílio de Éfeso'], note:'Uma decisão fundamental para a expansão do evangelho entre os não-judeus.' },
    { cat:'history', diff:4, q:'Durante os cerca de 400 anos entre o Antigo e o Novo Testamento, qual revolta judaica contra o domínio grego é notável?', opts:['Revolta dos Macabeus','Revolta de Bar Kokhba','Cerco de Massada','Guerra dos Sete Anos'], note:'Deu origem à festa judaica de Hanucá, celebrando a purificação do Templo.' },
    { cat:'history', diff:4, q:'Qual imperador romano é citado em Lucas como responsável pelo censo que levou Maria e José a Belém?', opts:['César Augusto','Tibério','Nero','Cláudio'], note:'"Naqueles dias saiu um decreto da parte de César Augusto..." (Lucas 2:1).' },
    { cat:'history', diff:4, q:'Qual governador romano da Judeia autorizou a crucificação de Jesus?', opts:['Pôncio Pilatos','Herodes Antipas','Félix','Festo'], note:'Ele "lavou as mãos" diante da multidão, mas ainda assim proferiu a sentença (Mateus 27:24).' },
];
